services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DB
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # if we want to save the db after shutdown
    # volumes:
      # - ./db:/var/lib/postgresql/data

  # db_test:
  #   build: .
  #   command: python3 -m unittest discover -s tests

  api:
    platform: linux/amd64
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '5000:5000'
    build: 
      context: ./
      dockerfile: ./Dockerfile
